version: '3.4'

services:

  userstoredb:
    container_name: userstoredb
    environment:
        MSSQL_SA_PASSWORD: "SVSEpwd2"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1430:1433"
    volumes:
      - uservolume:/var/opt/mssql/data

  complaintdb:
    container_name: complaintdb
    environment:
        MSSQL_SA_PASSWORD: "SVSEpwd2"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1431:1433"
    volumes:
      - complaintvolume:/var/opt/mssql/data

  useridentitystore.api:
    container_name: useridentitystore.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServerConnstr= Server=userstoredb;Database=UserStoreDB; User Id= SA ;Password= SVSEpwd2"
    depends_on:
      - userstoredb
    ports:
      - "9300:80"


